#!/usr/bin/env python
"""Legacy wrapper for baseline daily forecasting outputs."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Legacy entrypoint. Baseline predictions are generated by forecast_daily/generate_results.py."
        )
    )
    parser.add_argument("--model", choices=["transformer", "mamba", "gnn"], default="transformer")
    parser.add_argument("--csv", default=None, help="Optional CSV with columns: date, airnow_no2")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--results-dir", type=str, default="results")
    parser.add_argument("--train-end", type=str, default="auto")
    parser.add_argument(
        "--run",
        action="store_true",
        help="Run baseline generation now for the selected model. Without this flag, only print guidance.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parent
    results_dir = root / args.results_dir

    print("Baseline artifacts live under:", results_dir)
    print("Prediction CSV path:", results_dir / f"predictions_{args.model}.csv")

    if not args.run:
        print("Use --run to regenerate predictions for the selected model.")
        return

    target = root / "forecast_daily" / "generate_results.py"
    cmd = [
        sys.executable,
        str(target),
        "--models",
        args.model,
        "--epochs",
        str(args.epochs),
        "--batch-size",
        str(args.batch_size),
        "--lr",
        str(args.lr),
        "--seed",
        str(args.seed),
        "--results-dir",
        str(args.results_dir),
        "--train-end",
        str(args.train_end),
    ]
    if args.csv:
        cmd.extend(["--csv", args.csv])

    subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
